name: TASP
version: 0.0.3
main: tech.spencercolton.tasp.TASP
loadbefore: [TASPLocks, TASPPerms, TASPEconomy, TASPBackup]
commands:
    killall:
        description: "Kill all entities of a given type in a given radius."
        permission-message: "You do not have permisssion to do that."
        usage: "Invalid syntax. /killall [entity] [radius]"
    setspeed:
        description: Set the speed of a player.
        permission: tasp.setspeed
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /setspeed <speed> [player]"
    fly:
        description: Enable or disable fly mode for a player.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /fly [player]"
    home:
        description: Teleport a player home.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /home"
    sethome:
        description: Sets the home of a player.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /sethome"
    god:
        description: Sets god mode to enabled or disabled for a player.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /god [player]"
    setspawn:
        description: Sets the spawnpoint of a world.
        permission-message: You do not have permission to do that
        usage: "Invalid syntax. /setspawn [<x> <y> <z>] [world]"
    gamemode:
        description: Change a player''s gamemode.
        aliases: [gm]
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /gamemode <mode> [player]"
    time:
        description: View or change the world time.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax.  /time [newTime]"
    top:
        description: Go to the highest block in this column.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /top"
    afk:
        description: Set yourself AFK.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /afk [player]"
    xyz:
        description: Get your position in the world.
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /xyz"
    mute:
        description: Stop a player from talking.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /mute <player>"
    me:
        description: Perform an action.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /me <action>"
    msg:
        description: Send a private message.
        aliases: [message, send, tell]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /msg <player> <message>"
    reply:
        description: Reply to a private message.
        aliases: [r]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /r <message>"
    block:
        description: Block a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /block <player>"
    unblock:
        description: Unblock a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /unblock <player>"
    tasp:
        description: TASP administrative command.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /tasp [option]"
    broadcast:
        description: Broadcast a message.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax.  /broadcast <message>"
    powertool:
        description: Run a command by hitting with a block.
        aliases: [pt]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax.  /powertool [command line]"
    powertooltoggle:
        description: Enable or disable powertools for the whole server.
        aliases: [ptt]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /powertooltoggle"
    stalker:
        description: See messages sent to others.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /stalker [player]"
    info:
        description: See info about a player.
        aliases: [whois]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /info <player>"
    srvinfo:
        description: Get vital server info.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /srvinfo"
    stahp:
        description: Stop the server.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /stahp"
    shock:
        description: Shock a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /shock <player>"
    burn:
        description: Burn a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /burn <player> [time]"
    feed:
        description: Feed a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /feed [player] [amount]"
    starve:
        description: Starve a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /starve [player] [amount]"
    heal:
        description: Heal a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /heal [player] [amount]"
    hurt:
        description: Hurt a player.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /hurt [player] [amount]"
    fom:
        description: Make a player a friend of monsters.
        aliases: [disabletarget]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /fom [player]"
    potion:
        description: Give a player certain potion effects.
        aliases: [effect]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /potion <potion> [strength] [duration] [player]"
    antidote:
        description: Cure all status effects.
        aliases: [cleareffects]
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /antidote [player]"
    buddha:
        description: Don't allow death.
        permission-message: You do not have permission to do this.
        usage: "Invalid syntax. /buddha [player]"
    weather:
        description: View or change the weather.
        permission-message: You don't have permission to do this.
        usage: 'Invalid syntax. /weather [world [type]] | [type]'
    spawnmob:
        description: Spawn a mob.
        permission-message: You do not have permission to do this.
        usage: 'Invalid syntax. /spawnmob [mob] <amount>'