name: TASP
version: 0.0.3
main: tech.spencercolton.tasp.TASP
loadbefore: [TASPLocks, TASPPerms, TASPEconomy, TASPBackup]
commands:
    killall:
        description: "Kill all entities of a given type in a given radius."
        aliases: [bluerinse]
    setspeed:
        description: Set the speed of a player.
    fly:
        description: Enable or disable fly mode for a player.
    home:
        description: Teleport a player home.
    sethome:
        description: Sets the home of a player.
    god:
        description: Sets god mode to enabled or disabled for a player.
    setspawn:
        description: Sets the spawnpoint of a world.
    gamemode:
        description: Change a player''s gamemode.
        aliases: [gm]
    time:
        description: View or change the world time.
    top:
        description: Go to the highest block in this column.
    afk:
        description: Set yourself AFK.
    xyz:
        description: Get your position in the world.
    mute:
        description: Stop a player from talking.
    me:
        description: Perform an action.
    msg:
        description: Send a private message.
        aliases: [message, send, tell]
    reply:
        description: Reply to a private message.
        aliases: [r]
    block:
        description: Block a player.
    unblock:
        description: Unblock a player.
    tasp:
        description: TASP administrative command.
    broadcast:
        description: Broadcast a message.
    powertool:
        description: Run a command by hitting with a block.
        aliases: [pt]
    powertooltoggle:
        description: Enable or disable powertools for the whole server.
        aliases: [ptt]
    stalker:
        description: See messages sent to others.
    info:
        description: See info about a player.
        aliases: [whois]
    srvinfo:
        description: Get vital server info.
    stahp:
        description: Stop the server.
    shock:
        description: Shock a player.
    burn:
        description: Burn a player.
    feed:
        description: Feed a player.
    starve:
        description: Starve a player.
    heal:
        description: Heal a player.
    hurt:
        description: Hurt a player.
    fom:
        description: Make a player a friend of monsters.
        aliases: [disabletarget]
    potion:
        description: Give a player certain potion effects.
        aliases: [effect]
    antidote:
        description: Cure all status effects.
        aliases: [cleareffects]
    buddha:
        description: Don't allow death.
    weather:
        description: View or change the weather.
    spawnmob:
        description: Spawn a mob.
    world:
        description: Teleport to a world.
    explode:
        description: Create an explosion.
    drops:
        description: Remove item drops in a world.
        aliases: [clearlag, nolag, lagfix, fixlag]
    tp:
        description: Teleport to a player.
        aliases: [teleport]
    tphere:
        description: Teleport a player to you.
        aliases: [teleporthere]
    tpall:
        description: Teleport all players to you.
        aliases: [tpallhere, tpahere, teleportallhere, teleportall]
    tpa:
        description: Accept a teleport request.
        aliases: [tpaccept]
    tpd:
        description: Deny a teleport request.
        aliases: [tpdeny]
    tpr:
        description: Request to teleport to a player.
        aliases: [tprequest]
    tprhere:
        description: Request to teleport a player to you.
        aliases: [tprequesthere, teleportrequesthere, teleporthererequest, tphererequest, tpherer]
    tpar:
        description: Request all players to teleport to you.
        aliases: [tpallrhere, tparhere, teleportallrhere, teleportrall, tpallherer, tpaherer, teleportallherer, teleportallr, tpallrequesthere, tparequesthere, teleportallrequesthere, teleportrequestall, tpallhererequest, tpahererequest, teleportallhererequest, teleportallrequest]
    tpt:
        description: Enable or disable teleportation for the whole server.
        aliases: [tptoggle, teleporttoggle, teleportationtoggle]
    mail:
        description: Send or receive mail.
    back:
        description: Go back to your last location.
    spawn:
        description: Teleport to the world's spawn.
    shoot:
        description: Fire an entity.
    xp:
        description: Check or set experience points.
    craft:
        description: Open a crafting bench.
        aliases: [workbench, crafting]
    invspy:
        description: See someone else's inventory.
        aliases: [invsee]
    clear:
        description: Clear a player's inventory
        aliases: [ci]
    su:
        description: Make a player use a command
    tploc:
        description: Teleport to a location in a world.
    disappear:
        description: Vanish before everyone's eyes!
    jump:
        description: Jump to where you're looking.
    helpme:
        description: Ask online staff for help.
    nick:
        description: Change your nickname.
    recipe:
        description: Check the crafting recipe for an item.
    holding:
        description: What are you holding?
    i:
        description: Give yourself an item
    setwarp:
        description: Make a warp point in the world.
    warp:
        description: Jump to a set point in the world.