name: TASP
version: 0.0.1
main: tech.spencercolton.tasp.TASP
loadbefore: [TASPDoors, TASPPerms]
commands:
    killall:
        description: "Kill all entities of a given type in a given radius."
        permission: tasp.killall
        permission-message: "You do not have permisssion to do that."
        usage: "Invalid syntax. /killall [entity] [radius]"
    setspeed:
        description: Set the speed of a player.
        permission: tasp.setspeed
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /setspeed <speed> [player]"
    fly:
        description: Enable or disable fly mode for a player.
        permission: tasp.fly
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /fly [player]"
    home:
        description: Teleport a player home.
        permission: tasp.home
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /home"
    sethome:
        description: Sets the home of a player.
        permission: tasp.sethome
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /sethome"
    god:
        description: Sets god mode to enabled or disabled for a player.
        permission: tasp.god
        permission-message: You do not have permission to do that.
        usage: "Invalid syntax. /god [player]"
permissions:
    tasp.*:
        description: OP access to TASP plugin.
        default: op
        children:
            tasp.setspeed: true
            tasp.killall: true
    tasp.setspeed:
        description: Set the speed of a player.
        default: op
    tasp.setspeed.others:
        description: Set the speed of another player.
        default: op
        children:
            tasp.setspeed: true
    tasp.killall:
        description: Kill all entites of a given type in a given radius.
        default: op
    tasp.fly:
        description: Set fly mode of a player.
        default: op
    tasp.fly.others:
        description: Set the fly mode of another player.
        default: op
        children:
            tasp.fly: true
    tasp.home:
        description: Teleport a player home.
        default: true
    tasp.home:
        description: Sets the home of a player.
        default: true
    tasp.god:
        description: Set the god mode of a player.
        default: op
    tasp.god.others:
        description: Set the god mode of another player.
        default: op
        children:
            tasp.god: true